api_version = "unstable"

[[extensions]]
name = "checkout-ui"
handle = "checkout-ui"
type = "ui_extension"
uid = "fddfc370-27c7-c30f-4ee0-a927194e2accadefd40c"

[[extensions.targeting]]
module = "./src/GiftCardRedeem.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true

[extensions.capabilities.network_domains]
allowed_domains = [
  "night-prepare-ben-waters.trycloudflare.com",
  "srl-ts.ogloba.com"
]