# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d337c566f3e347f8bb12592797cb7771"
name = "Ogloba-giftcard-redemption"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01" 

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks"

[access_scopes]
scopes = "write_discounts, write_products,read_orders"

[auth]
redirect_urls = [
  "https://night-prepare-ben-waters.trycloudflare.com/auth/callback",
  "https://night-prepare-ben-waters.trycloudflare.com/auth/shopify/callback",
  "https://night-prepare-ben-waters.trycloudflare.com/api/auth"
]
